service: lambda-flask

provider:
  name: aws
  runtime: python3.7
  region: us-east-1
  memorySize: 128


plugins:
  - serverless-wsgi

custom:
  wsgi:
    app: app.app

functions:
  app:
    handler: wsgi_handler.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'
